### ISSUE TITLE
unity build bug

### ISSUE THREAD

**Issue by coolishbee** [aleab/cef-unity-sample#1]
hi~There was a mission to show Chrome in Unity, so I decided to use it. And it works well in Unity Editor and I liked it.
It works well in Unity Editor, but exe files built do not work.

**Comment by aleab** [comment]
Works fine for me on Unity version 5.6.0 as it did 7 months ago.

Unfortunately there's no way I can help you if you don't include more information. Are you trying to run this project as-is or did you include it in some other project of your own? Which Unity version are you using? Which Windows version? Does the application just not start or does it crash? Have you tried launching it as Administrator? Any log file or stacktrace I can have a look into? (log files are usually written in the same directory the *exe* file is into or inside the *\*_Data* directory)

**Comment by coolishbee** [comment]
![bug1](https://user-images.githubusercontent.com/20632507/33467254-8bf5410a-d696-11e7-930a-00f501ea317f.png)
![bug2](https://user-images.githubusercontent.com/20632507/33467256-8ee04f68-d696-11e7-81dd-e7e2e8c3ea0a.png)
![bug3](https://user-images.githubusercontent.com/20632507/33467259-91cedea6-d696-11e7-8d35-c1545870ac4e.png)
![bug4](https://user-images.githubusercontent.com/20632507/33467263-93e548ec-d696-11e7-8a44-e039811b1aa5.png)

**Comment by coolishbee** [comment]
thank you for the reply.
As you can see in the screenshot
-unity version 5.6.0p4(64bit)
-windows 10
The project is a sample and it did not start or crash.The project is a sample and it did not start or crash. 
However, this does not happen in the mesh.

**Comment by aleab** [comment]
The mesh colour is pink probably because somehow the Mesh Renderer has no material attached at runtime. I don't really know what's going on there, though.
Can I have a look at that *"cef.log"* file and at any *"\*.log"* file inside the *jaychun_Data* directory?

Also, I'd suggest you to carefully debug the application starting from the *OffscreenCEF* class to see what happens at runtime. I can see that you have Visual Studio installed; you can easily attach its debugger to Unity and set breakpoints in the code.

**Comment by coolishbee** [comment]
Thanks.This is solved! The problem was missing material. In the editor, the problem is not known because it is set as the default material.

**Comment by coolishbee** [comment]
I'm sorry, but there is one more question. It is to launch your webcam from Chrome. For example, I've been working like a snapshot in .NET, but I wonder if it's possible in Unity. What should I do? Is there a way?

**Comment by coolishbee** [comment]
![test](https://user-images.githubusercontent.com/20632507/33542177-3f480bd6-d915-11e7-8875-c1805bed0197.png)

**Comment by aleab** [comment]
Can you be a bit more specific? What are you trying to achieve?

If you are trying to capture images from the webcam and display them somewhere on the scene, CEF is not the right approach, in my opinion. You should take a look at some third party library like [Emgu CV](http://www.emgu.com/wiki/index.php/Main_Page) or .NET wrappers of some native library like [DirectShow.NET](http://directshownet.sourceforge.net/) or [Media Foundation .NET](http://mfnet.sourceforge.net/).

However, if you just want the website you are navigating to be able to use the webcam, then the *"enable-media-stream"* parameter should be enough.

**Comment by coolishbee** [comment]
I would like to display the video that is being recorded in real-time camera on my smartphone as video on web chrome. I tried this "enable-media-stream" parameter, but it did not work. I do not know how wrong this is.

**Comment by coolishbee** [comment]
![kakaotalk_20171205_201218886](https://user-images.githubusercontent.com/20632507/33604269-9de2620c-d9f8-11e7-95f0-a784ebb4a759.png)

**Comment by aleab** [comment]
Your first sentence is a bit ambiguous. I'm gonna assume that the smartphone is the one doing the recording and that you want to display what is being recorded somewhere in a Unity scene in real-time. Is that correct?
Why do you think you need CEF to accomplish that? Is the video recorded by your smartphone being streamed somewhere in the internet?

As far as I know (and I don't know much about it) that *"enable-media-stream"* parameter only allows you access the media stream of the camera and microphone of the device that is using Chrome.

**Comment by coolishbee** [comment]
Yes. I want to show it on Unity screen. I want to shoot with a smartphone device and display the screen in real time. It's like a screenshot. However, enable-media-stream does not allow access.

**Comment by coolishbee** [comment]
![test12](https://user-images.githubusercontent.com/20632507/33821945-197fd940-de99-11e7-91c1-fe865a3efa76.png)

**Comment by coolishbee** [comment]
I want to display that video screen on a quad mesh in the unity screen.

**Comment by aleab** [comment]
Can you access the video being recorded by the smartphone in real-time through a URL?
CEF is an embeddable web browser. If the video output of your smartphone is not available in the internet or in your local network via a URL, then CEF is useless.

To achieve what you want with CEF you have to use a live streaming service on your smartphone to stream the video on the internet and use CEF in Unity to display the web page where that streamed video is available at. I'm talking about Twitch.tv, for example. I doubt that's what you want, though.

The *"enable-media-stream"* option is unnecessary in your case. It just allows you to access the webcam of the device running CEF, that is not your smartphone.

You are better off not using CEF at all if you don't want to display web pages.
What you should do is something like what's described in [this web page](http://www.firstpost.com/tech/news-analysis/how-to-stream-video-from-your-android-device-to-a-pc-and-vice-versa-3587791.html).
